CREATE TABLE apartamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(10) NOT NULL,
    bloco_id BIGINT NOT NULL,

CONSTRAINT fk_apartamento_bloco
    FOREIGN KEY (bloco_id)
    REFERENCES bloco(id),

CONSTRAINT uk_apartamento_bloco_numero
    UNIQUE (bloco_id, numero)
);